### ISSUE TITLE
PCB Updated with 3d packages

### ISSUE THREAD

**Issue by mbt28** [freeDSP/freeDSP-CLASSIC-SMD-BALANCED#1]
Hi,

I updated the pcb with built-in 3d packages of KiCAD. All the units have their 3d shapes beside P2 Power Barrel Jack and P12. You can find the rendered images below. If you are interested in to update the github source I can share the files.

![image](https://user-images.githubusercontent.com/14265206/80700042-519ef980-8add-11ea-9e72-efd48754034b.png)

![image](https://user-images.githubusercontent.com/14265206/80699749-cc1b4980-8adc-11ea-87ba-7a09d72c0f0d.png)

Have a nice day

**Comment by BasssT** [comment]
Very nice. Thanks. I give you rights to update the repo if you like.
